fdfs:
  so-timeout: 600000
  connectTimeout: 600
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  pool:
    jmx-enabled: false
    max-total: 200
    max-wait-millis: 30000
  trackerList:            #TrackerList参数,支持多个
    - 自己ip:22122   
  visit:
    url: http://自己ip  
    port: 8888
